# Generated by Django 4.2 on 2024-06-29 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
        ("users", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_data",
                    models.DateField(auto_now_add=True, verbose_name="Дата оплаты"),
                ),
                ("pay_summ", models.IntegerField(verbose_name="Оплаченная сумма")),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("NAL", "Наличные"), ("TRANSFER", "Перевод")],
                        max_length=10,
                        verbose_name="Тип оплаты",
                    ),
                ),
                (
                    "payd_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.course",
                        verbose_name="оплаченный курс",
                    ),
                ),
                (
                    "payd_lessons",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.lessons",
                        verbose_name="оплаченный урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
