# Generated by Django 4.2 on 2024-06-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={"verbose_name": "платеж", "verbose_name_plural": "платежи"},
        ),
    ]
