# Generated by Django 4.2 on 2024-07-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_remove_subscription_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="amount",
            field=models.PositiveIntegerField(
                default=1000, verbose_name="Стоимость курса"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Стоимость курса"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="id сессии"
            ),
        ),
    ]
