# Generated by Django 4.2 on 2024-07-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "materials",
            "0005_course_amount_subscription_amount_subscription_link_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="product",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="название продукта"
            ),
        ),
    ]
