# Generated by Django 4.2 on 2024-07-04 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "materials",
            "0008_remove_amounts_amount_remove_amounts_subscription_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amounts",
            name="course",
        ),
        migrations.AddField(
            model_name="amounts",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Стоимость курса"
            ),
        ),
        migrations.AlterField(
            model_name="amounts",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
    ]
