# Generated by Django 4.2 on 2024-07-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0009_remove_amounts_course_amounts_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="дата и время последнего обновления"
            ),
        ),
    ]
