# Generated by Django 4.2 on 2024-07-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0010_course_last_update_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="amount",
            field=models.IntegerField(blank=True, null=True, verbose_name="Цена курса"),
        ),
    ]
